"use client";
import { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import AppWrapper from "@/components/AppWrapper";
import Navbar from "@/components/custom/navbar/Navbar";
import { ThemeProvider } from "next-themes";
import { Toaster } from "@/components/ui/toaster";
import { usePathname } from "next/navigation";
import { TooltipProvider } from "@/components/ui/tooltip";

const inter = Outfit({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const Layout = ({ children }: { children: React.ReactNode }) => {
  const pathname = usePathname();
  const isDashboard = pathname.split("/").includes("dashboard");

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {isDashboard ? (
          <>
            <TooltipProvider>{children}</TooltipProvider>
            <Toaster />
          </>
        ) : (
          <ThemeProvider attribute="class">
            <div
              className="dark:bg-gray-800 min-h-screen bg-gray-100 dark:text-gray-300 text-gray-900
          transition-all duration-1000"
            >
              <AppWrapper>
                <Navbar />
                {children}
                <Toaster />
              </AppWrapper>
            </div>
          </ThemeProvider>
        )}
      </body>
    </html>
  );
};

export default Layout;
